# Generated by Django 5.0.3 on 2024-07-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=100)),
                ('a_pic', models.ImageField(upload_to='actors/')),
                ('a_bio', models.TextField()),
                ('a_nationality', models.CharField(max_length=100)),
                ('a_awards', models.CharField(max_length=100)),
                ('a_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('a_birthdate', models.DateField()),
                ('a_city', models.ForeignKey(db_column='a_city', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.city')),
                ('a_country', models.ForeignKey(db_column='a_country', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.country')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=100)),
                ('d_pic', models.ImageField(upload_to='directors/')),
                ('d_bio', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('d_city', models.ForeignKey(db_column='d_city', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.city')),
                ('d_country', models.ForeignKey(db_column='d_country', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.country')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(to='MovieFlix.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.genre')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.country')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='d_state',
            field=models.ForeignKey(db_column='d_state', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.state'),
        ),
        migrations.AddField(
            model_name='actor',
            name='a_state',
            field=models.ForeignKey(db_column='a_state', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.state'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_dp', models.ImageField(upload_to='users/')),
                ('u_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_phone', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('u_city', models.ForeignKey(db_column='u_city', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.city')),
                ('u_country', models.ForeignKey(db_column='u_country', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.country')),
                ('u_state', models.ForeignKey(db_column='u_state', on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.state')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFlix.user')),
            ],
        ),
    ]
